name: Run Typescript to update README blog posts

on:
  # pull_request:
  schedule:
     - cron: '0 * * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      # - name: Update README
      #   run: npm run update-readme

      # - name: Scrape posts and update README
      #   run: node scripts/update-readme-blog-posts.ts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REPOSITORY: $GITHUB_REPOSITORY            

      - name: Lint code
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint
        
      - name: Update README by running typescript file
        # if: ${{ github.event_name == 'pull_request' }}
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: npm run update-readme

      - name: Diff?
        run: git diff

      - name: Commit
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          git status 
          
          git status | grep 'nothing to commit' && exit 0

          git config --global user.name "9opsec"
          git config --global user.email "9opsec@users.noreply.github.com"

          date=$(date '+%Y-%m-%d-%H-%M')
          git checkout main
          git add README.md
          git commit -m "update blog posts in readme ($date)"
          git push origin main
